<?php

/**
 * Implements hook_views_api().
 */
function views_timelinejs_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'views_timelinejs') . '/views',
  );
}

/**
 * Implementation of hook_theme()
 */
function views_timelinejs_theme() {
  return array(
    'views_timelinejs_link_to_entity' => array(
      'file' => 'theme/views_timelinejs.theme.inc',
      'arguments' => array(
        'uri' => NULL,
        'link_text' => NULL,
      ),
    ),
  );
}

/**
 * Function to include TimelineJS libraries
 */
function views_timelinejs_load_libraries() {
  // Include TimelineJS libraries (Libraries API 1.x)
  if ($path = libraries_get_path('timeline')) {
    drupal_add_css($path . '/compiled/css/timeline.css');
    drupal_add_js($path . '/compiled/js/storyjs-embed.js');
  }
  else {
    drupal_set_message(t('TimelineJS libraries not found in libraries/timeline directory. Timeline will not work.'), 'error', FALSE);
  }
}
