<?php

/**
 * Implements hook_views_api().
 */
function views_timelinejs_views_api() {
  return array(
    'api' => '3',
  );
}

/**
 * Implements hook_menu().
 */
function views_timelinejs_menu() {
  $items['_timelinejs'] = array(
    'page callback' => 'views_timelinejs_get_timeline_json',
    'delivery callback' => 'views_timelinejs_deliver_json',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Function to load a view, return view results in JSON format
 */
function views_timelinejs_get_timeline_json($view_name, $display_id) {
  $arguments = func_get_args();
  $args = array();
  // Shift two first function arguments off and rebuild from [0]
  foreach($arguments as $count => $arg) {
    if($count > 1) {
      $args[] = $arg;
    }
  }

  // Load the specified View.
  $view = views_get_view($view_name);
  if(is_object($view) && isset($view->name)) {
    $view->set_display($display_id);

    // Set arguments that were received from URL call
    if(is_array($args)) {
      $view->set_arguments($args);
    }
    // Set a variable that makes theming layer output JSON instead of standard markup
    $view->json = TRUE;

    if ($view->access($display_id)) {
      $output = $view->execute_display($display_id);
      $view->destroy();
      // Strip all markup from output, we want just the pure JSON data
      return trim(strip_tags($output['content']));
    }
    $view->destroy();
  }
  // View couldn't be loaded, output nothing
  else {
    exit();
  }
}

/**
 * Function to include TimelineJS libraries
 */
function views_timelinejs_load_libraries() {
  // Include TimelineJS libraries (Libraries API 1.x)
  if ($path = libraries_get_path('timeline')) {
    drupal_add_js($path . '/compiled/js/storyjs-embed.js');
  }
}

/**
 * Delivery callback to output Drupal data as JSON
 */
function views_timelinejs_deliver_json($page_callback_result) {
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
  print($page_callback_result);
}